export interface Guide {
  id: string;
  name: string;
  location: string;
  pricePerHour: number;
  rating: number;
  reviewCount: number;
  languages: string[];
  category: string;
  bio: string;
  imageUrl: string;
}
export const LOCATIONS = ['Paris, France', 'Tokyo, Japan', 'Rome, Italy', 'New York, USA', 'Barcelona, Spain', 'Kyoto, Japan', 'London, UK', 'Berlin, Germany'];
export const CATEGORIES = ['Historical', 'Food & Drink', 'Adventure', 'Cultural', 'Photography', 'Art & Museums'];
export const LANGUAGES = ['English', 'Spanish', 'French', 'German', 'Japanese', 'Italian', 'Mandarin', 'Portuguese'];
export const MOCK_GUIDES: Guide[] = [
  {
    id: '1',
    name: 'Elena Rossi',
    location: 'Rome, Italy',
    pricePerHour: 45,
    rating: 4.9,
    reviewCount: 128,
    languages: ['English', 'Italian', 'Spanish'],
    category: 'Historical',
    bio: 'Archaeologist by training, I love bringing the ancient ruins of Rome to life. Specializing in the Colosseum and Roman Forum tours.',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '2',
    name: 'Kenji Tanaka',
    location: 'Tokyo, Japan',
    pricePerHour: 60,
    rating: 5.0,
    reviewCount: 85,
    languages: ['English', 'Japanese'],
    category: 'Food & Drink',
    bio: 'Let me take you to the best hidden izakayas and sushi spots in Tokyo. I am a food writer and local culinary expert.',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '3',
    name: 'Sophie Martin',
    location: 'Paris, France',
    pricePerHour: 55,
    rating: 4.8,
    reviewCount: 210,
    languages: ['English', 'French', 'German'],
    category: 'Art & Museums',
    bio: 'Art historian specializing in the Louvre and Musée d\'Orsay. Skip the line and understand the masterpieces with a local expert.',
    imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '4',
    name: 'James Wilson',
    location: 'London, UK',
    pricePerHour: 50,
    rating: 4.7,
    reviewCount: 95,
    languages: ['English'],
    category: 'Historical',
    bio: 'Blue Badge guide with a passion for royal history and hidden London alleys. From the Tower of London to Westminster.',
    imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '5',
    name: 'Yuki Sato',
    location: 'Kyoto, Japan',
    pricePerHour: 40,
    rating: 4.9,
    reviewCount: 150,
    languages: ['English', 'Japanese', 'Mandarin'],
    category: 'Cultural',
    bio: 'Experience the zen of Kyoto\'s temples and gardens. I can also arrange tea ceremonies and geisha district walking tours.',
    imageUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '6',
    name: 'Carlos Rodriguez',
    location: 'Barcelona, Spain',
    pricePerHour: 35,
    rating: 4.6,
    reviewCount: 78,
    languages: ['English', 'Spanish', 'Catalan'],
    category: 'Architecture',
    bio: 'Gaudí enthusiast! I will show you the secrets of Sagrada Família, Park Güell, and the modernist architecture of Barcelona.',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '7',
    name: 'Sarah Jenkins',
    location: 'New York, USA',
    pricePerHour: 75,
    rating: 4.8,
    reviewCount: 300,
    languages: ['English', 'Spanish'],
    category: 'Photography',
    bio: 'Professional photographer and guide. I know all the best angles for the Brooklyn Bridge, Times Square, and Central Park.',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '8',
    name: 'Hans Mueller',
    location: 'Berlin, Germany',
    pricePerHour: 45,
    rating: 4.7,
    reviewCount: 112,
    languages: ['English', 'German', 'Russian'],
    category: 'Historical',
    bio: 'Specializing in Cold War history and the Berlin Wall. Let\'s explore the fascinating and complex history of this city.',
    imageUrl: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '9',
    name: 'Maria Silva',
    location: 'Lisbon, Portugal',
    pricePerHour: 30,
    rating: 4.9,
    reviewCount: 60,
    languages: ['English', 'Portuguese', 'Spanish'],
    category: 'Food & Drink',
    bio: 'Pastel de Nata lover! Join me for a food tour through Alfama and taste the best local wines and seafood.',
    imageUrl: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '10',
    name: 'David Chen',
    location: 'San Francisco, USA',
    pricePerHour: 80,
    rating: 5.0,
    reviewCount: 45,
    languages: ['English', 'Mandarin'],
    category: 'Adventure',
    bio: 'Hiking and biking tours across the Golden Gate Bridge and into the Marin Headlands. For active travelers!',
    imageUrl: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '11',
    name: 'Isabella Conti',
    location: 'Florence, Italy',
    pricePerHour: 50,
    rating: 4.8,
    reviewCount: 180,
    languages: ['English', 'Italian', 'French'],
    category: 'Art & Museums',
    bio: 'Renaissance art expert. I offer in-depth tours of the Uffizi Gallery and the Accademia to see David.',
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '12',
    name: 'Liam O\'Connor',
    location: 'Dublin, Ireland',
    pricePerHour: 40,
    rating: 4.7,
    reviewCount: 90,
    languages: ['English'],
    category: 'Cultural',
    bio: 'Pub culture, literary history, and folklore. Experience the craic in Dublin\'s best historic pubs.',
    imageUrl: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '13',
    name: 'Aiko Yamamoto',
    location: 'Osaka, Japan',
    pricePerHour: 45,
    rating: 4.8,
    reviewCount: 70,
    languages: ['English', 'Japanese'],
    category: 'Food & Drink',
    bio: 'Osaka is the kitchen of Japan! I\'ll show you the best street food in Dotonbori and hidden local favorites.',
    imageUrl: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '14',
    name: 'Jean-Luc Dubois',
    location: 'Paris, France',
    pricePerHour: 65,
    rating: 4.6,
    reviewCount: 110,
    languages: ['English', 'French'],
    category: 'Photography',
    bio: 'Night photography tours of the City of Lights. Learn how to capture Paris illuminated at night.',
    imageUrl: 'https://images.unsplash.com/photo-1521119989659-a83eee488058?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  },
  {
    id: '15',
    name: 'Emma Thompson',
    location: 'London, UK',
    pricePerHour: 55,
    rating: 4.9,
    reviewCount: 140,
    languages: ['English', 'Spanish'],
    category: 'Adventure',
    bio: 'Harry Potter filming locations walking tour. Magical spots across London for fans of the wizarding world.',
    imageUrl: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-1.2.1&auto=format&fit=crop&w=256&q=80',
  }
];